[build]
  command = "CI= npm run build --verbose && rm -rf .cache node_modules && npm install && npm run build"
  publish = "build"
[build.environment]
  NODE_VERSION = "20"
  HUGO_VERSION = "0.117.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200